from kimi_utils import *
_command_map = {
    'ls': 'Get-ChildItem',
    'ver': '$PSVersionTable',
    'dir': 'Get-ChildItem',  # bash dir is different, but usually means ls
    'cd': 'Set-Location',
    'pwd': 'Get-Location',
    'cat': 'Get-Content',
    'mkdir': 'New-Item -ItemType Directory',
    'rm': 'Remove-Item',
    'cp': 'Copy-Item',
    'mv': 'Move-Item',
    'grep': 'Select-String',
    'ps': 'Get-Process',
    'kill': 'Stop-Process',
    'echo': 'Write-Output',
    'touch': 'New-Item -ItemType File',
    'which': 'Get-Command',
    'wc': 'Measure-Object',
    'man': 'Get-Help',
    'find': 'Get-ChildItem -Recurse',
    'head': 'Select-Object -First',
    'tail': 'Get-Content -Tail',
    'sleep': 'Start-Sleep',
    'clear': 'Clear-Host',
    'exit': 'Exit',
    'history': 'Get-History',
    'alias': 'Get-Alias',
    'unalias': 'Remove-Item alias:',
    'df': 'Get-Volume',
    'du': 'Get-ChildItem -Recurse | Measure-Object -Property Length -Sum',
    'chmod': 'Set-ItemProperty',
    'chown': 'Set-Acl',
    'diff': 'Compare-Object',
    'env': 'Get-ChildItem env:',
    'tee': 'Tee-Object',
    'time': 'Measure-Command',
    'date': 'Get-Date',
    'whoami': 'whoami',
    'hostname': 'hostname',
    'uname': 'Get-ComputerInfo',
    'uptime': 'Get-Uptime',
    'id': 'whoami /user',
    'groups': 'whoami /groups',
    'ln': 'New-Item -ItemType SymbolicLink',
    'ln -s': 'New-Item -ItemType SymbolicLink',
    'readlink': 'Get-Item',
    'realpath': 'Resolve-Path',
    'basename': 'Split-Path -Leaf',
    'dirname': 'Split-Path -Parent',
    'mktemp': 'New-TemporaryFile',
    'xargs': 'ForEach-Object',
    'yes': 'while ($true) { Write-Output "y" }',
    'seq': '1..',
    'shuf': 'Get-Random',
    'uniq': 'Get-Unique',
    'cut': 'ForEach-Object { $_.Split(" ") }',
    'paste': 'Join-String',
    'tr': 'ForEach-Object { $_ -replace }',
    'fold': 'Format-Wide',
    'split': 'Split-Path',
    'join': 'Join-Path',
    'tar': 'tar',
    'gzip': 'Compress-Archive',
    'gunzip': 'Expand-Archive',
    'zip': 'Compress-Archive',
    'unzip': 'Expand-Archive',
    'rsync': 'robocopy',
    'scp': 'Copy-Item',
    'ssh': 'ssh',
    'nc': 'Test-NetConnection',
    'ping': 'Test-Connection',
    'netstat': 'Get-NetTCPConnection',
    'ifconfig': 'Get-NetIPAddress',
    'ip': 'Get-NetIPAddress',
    'route': 'Get-NetRoute',
    'nslookup': 'Resolve-DnsName',
    'dig': 'Resolve-DnsName',
    'host': 'Resolve-DnsName',
    'curl': 'Invoke-WebRequest',
    'wget': 'Invoke-WebRequest',
    'jq': 'ConvertFrom-Json',
    'base64': '[Convert]::ToBase64String',
    'md5sum': 'Get-FileHash -Algorithm MD5',
    'sha256sum': 'Get-FileHash -Algorithm SHA256',
    'sha512sum': 'Get-FileHash -Algorithm SHA512'
}


for i in _command_map:
    prompt(f'''
Write a parser function:
def _convert_{i}(cmd: str) -> str: ...
to convert bash command "{i}" to powershell command, make sure all type of arguments in this command is well processed. '/C' '/V' should be consider equal to'-C', '-V'. 
add to to_powershell_cmd.py
           ''')
    clear_context()